#!/bin/bash

# scripts/pass-env.sh
# Securely populates .env.local with secrets from Proton Pass using pass-cli

ENV_FILE=".env.local"
ITEM_TITLE="Candera Etsy API"
VAULT_NAME="Google"

echo "Configuring .env.local from Proton Pass (pass-cli)..."

if ! command -v pass-cli >/dev/null 2>&1; then
    echo "Error: pass-cli is not installed. Please install it to sync environment variables."
    exit 1
fi

if ! command -v jq >/dev/null 2>&1; then
    echo "Error: jq is not installed. Please install it to parse secret data."
    exit 1
fi

# Fetch the item JSON
# We use the title and vault name to locate it.
ITEM_JSON=$(pass-cli item view --item-title "$ITEM_TITLE" --vault-name "$VAULT_NAME" --output json 2>/dev/null)

if [ -z "$ITEM_JSON" ]; then
    echo "Error: Could not find item '$ITEM_TITLE' in vault '$VAULT_NAME'."
    exit 1
fi

echo "Found '$ITEM_TITLE'. Syncing variables..."

# Clear or create .env.local
echo "# Generated by scripts/pass-env.sh" > "$ENV_FILE"

# Extract fields and write to .env.local
# This parses the nested structure: item.content.content.Custom.sections[].section_fields[]
echo "$ITEM_JSON" | jq -r '
  .item.content.content.Custom.sections[].section_fields[] 
  | "\(.name)=\"\(.content | to_entries[0].value)\""
' >> "$ENV_FILE"

# Add non-secret defaults
echo "ETSY_LISTINGS_LIMIT=50" >> "$ENV_FILE"
echo "VITE_ETSY_SHOP_URL=https://www.etsy.com/shop/CanderaCandles" >> "$ENV_FILE"

echo "Done. .env.local has been updated."
